info:
  version: '@project.version@'
  modulo: '@project.name@'

server:
  port: 8888

config:
  url-files: 'C:\Users\renan\Downloads\'

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/db_ir
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver