info:
  version: '@project.version@'
  modulo: '@project.name@'

server:
  port: 8888

config:
  url-files: 'C:\Users\renan\Downloads\'
  datasource:
      url: localhost
      username: root
      password: root